### PR TITLE
update for latest zig

### PR DESCRIPTION
**Pull request by andrewrk**

### CODE REVIEW

**Comment by andrewrk** [comment]
(unrelated to the PR)

check it out, I adapted the example to use xcb directly rather than glfw:

image

[source](https://codeberg.org/andrewrk/daw)

btw I think the custom build step (ShaderCompileStep) would be better off as a Run step. You can still provide the same API but it will be less fragile to use the existing std lib Run step.

**Comment by Snektron** [comment]
Nice! Yes, I've been meaning to get rid of the ShaderCompileSteps entirely.

Looks like is one instance of the old names remaining in test/ref_all_decls.zig, should be good otherwise.

**Comment by andrewrk** [comment]
Hmm, how come I can't trigger this with `zig build test`?

```
andy@bark ~/s/vulkan-zig (master)> zig build test --summary all
Build Summary: 3/3 steps succeeded; 9/9 tests passed
test success
└─ run test 9 passed 1ms MaxRSS:2M
   └─ zig test Debug native success 1s MaxRSS:290M
andy@bark ~/s/vulkan-zig (master)> zig version
0.14.0-dev.1392+37df6ba86
```

**Comment by Snektron** [comment]
Thanks!

**Pull request merged**
