### PR TITLE
[TMP FIX] Convert all multiline strings to regular strings

### PR DESCRIPTION
**Pull request by brodeuralexis**
As of Zig `0.10.0-dev.580+53e6c719e`, multiline strings appear to be broken.

zigbuild

This PR changes all faulty multiline strings into regular strings.
zigbuild-works

This PR is not to be merged, as I believe this issue will be fixed in the future in Zig's *master* branch.

I am simply leaving it here to advertise it as others may find it useful.

### CODE REVIEW

**Comment by Snektron** [comment]
Is there a relevant upstream issue?

**Comment by brodeuralexis** [comment]
Not sure, I am still looking through the issue tracker.

**Comment by Snektron** [comment]
Could this be a problem with windows line endings?

**Comment by maxxnino** [comment]
Yeah that exactly my first error when using vulkan-zig. All the windows glory crlf https://github.com/Snektron/vulkan-zig/issues/20

**Comment by Snektron** [comment]
Seems like this is resolved

**Comment by brodeuralexis** [comment]
Maybe consider adding a `.gitattributes` file with the following :
```
*.zig text eol=lf
```

**Pull request closed without merging**
