### PR TITLE
Duck typing verification made easier

### PR DESCRIPTION
**Pull request by InKryption**
I find that I keep making wrappers around these to make it easier to duck-type them in, as well as verify that the ducked-type pertains to a result of one of the Wrapper type functions, and I figured it may be worthwhile to share.
Completely understandable if this is rejected on the grounds that it is a breaking change (albeit a minor one), in exchange for a non-global use-case. My personal use case for this lies mainly in making and using functions which only care about one or two particular capabilities of a vtable parameter, without having to rely on the looseness of duck-typing.

Addendum: it was after the last pull request I made about changing the `{}Wrapper` type functions to take in a slice of `{}Command` that I realized I hadn't entirely solved the issue of `comptime` memoization over generic functions, since `comptime` slices in stage1 are not guaranteed to be equal regardless of contents, due to possibly different pointers, so this is also, in part, a sort of amendment to that.

### CODE REVIEW

**Comment by Snektron** [comment]
Something that was on my mind was to provide easier ways of combining function pointers from multiple extensions. My plan was to predefine a `[]Command` for every extension, which you would be able to concatenate at build to get the complete list of commands. I think that would look something along the lines of
```
const commands = vk.device_commands.v1_0
  ++ vk.device_commands.swapchain
  ++ (if (windows) vk.device_commands.win32_surface else .{});
```
I haven't really experimented with syntax like this yet though. One advantage of this type of system over bools is that it's much easier to include multiple commands at the same time.

Can you point me to your use-case of a feature like this?

**Comment by InKryption** [comment]
@Snektron The main goal of this change lies in the value of using a struct vs using a slice; where using a `comptime` slice can lead to multiple instances of what is functionally the same type, using an explicit struct value is guaranteed to always produce the same type for the same contents. This ultimately makes it easier to implement a function like this (when used in tandem with the other changes):
```zig
const std = @import("std");
const vk = @import("vulkan");
fn isInstanceWrapper(comptime T: type) bool {
    if (@typeInfo(T) != .Struct) return false;
    if (!@hasDecl(T, "commands")) return false;
    if (!std.meta.declarationInfo(T, "commands").is_pub) return false;
    return vk.InstanceWrapper(T.commands) == T;
}
```

This can then be subsequently used for type verification in other functions, which can then also do something like: `comptime assert(@TypeOf(instance_dispatch).commands.{required command});`.

I can definitely see the value in your method, though I could also argue that such a capability isn't made impossible by this change, just slightly more verbose, whilst your approach doesn't make it possible to make guarantees while using the duck-typing method.

If you do veto this, then the change I would subsequently request is to at least include the `cmds` parameter as a `commands` declaration inside the Wrapper types, which, while it wouldn't be nearly as ergonomic or provide the same type-consistency, would be an acceptable trade-off for me.

**Comment by ashpil** [comment]
> Something that was on my mind was to provide easier ways of combining function pointers from multiple extensions. My plan was to predefine a []Command for every extension, which you would be able to concatenate at build to get the complete list of commands. 

It seems to me @InKryption's modifications would provide a better system for this. If you treat wrapper inputs as just normal flags, rather than an array (which technically allows repeating a command more than once), you could just do something like:
```zig
const commands =
  vk.device_commands.v1_0.union(
  vk.device_commands.swapchain.union(
  if (windows) vk.device_commands.win32_surface else .{}));
```
which although possibly less ergonomic makes more semantic sense, I think - as what you're doing is identical to any other union-of-flags-ing that you might be doing in Vulkan.

**Comment by Snektron** [comment]
Yes that is true. I think I am convinced.

One question though; do you think its a good its a good idea to accept an EnumSet instead of en EnumFieldStruct? This already provides the relevant set operations.

**Comment by InKryption** [comment]
@Snektron After the change, the declaration for `{0s}CommandSet` does become a bit ugly:
```zig
\\pub const {0s}CommandSet = {0s}CommandSet: {{
\\    @setEvalBranchQuota(3000);
\\    break :{0s}CommandSet std.enums.EnumSet({0s}Command);
\\}};
```
Because the `EnumSet` has to iterate over every field a good few times. Not a big deal, but then: the procedure for defining the Wrapper types with your suggestion becomes something like:
```zig
const InstanceDispatch = vk.InstanceWrapper(blk: {
    @setEvalBranchQuota(10_000);
    break :blk vk.InstanceCommandSet.init(.{
        .destroyInstance = true,
        .createDevice = true,
        .destroySurfaceKHR = true,
        .enumeratePhysicalDevices = true,
        .getPhysicalDeviceProperties = true,
        .enumerateDeviceExtensionProperties = true,
        .getPhysicalDeviceSurfaceFormatsKHR = true,
        .getPhysicalDeviceSurfacePresentModesKHR = true,
        .getPhysicalDeviceSurfaceCapabilitiesKHR = true,
        .getPhysicalDeviceQueueFamilyProperties = true,
        .getPhysicalDeviceSurfaceSupportKHR = true,
        .getPhysicalDeviceMemoryProperties = true,
        .getDeviceProcAddr = true,
    });
);
```
Because the `init` function provided by `EnumSet` also needs to iterate over all of the fields, and quickly uses up the eval branch quota. We could define a struct with an `EnumSet` member, and wrap the functions in which we raise the eval branch quota, but at that point we may as well just define the functions manually, for the precise use cases required, without that level of indirection.

All that considered, what would you prefer? And if you decide that we should define our own functions, would you like me to do that in this PR, or will you do it in a separate PR?

**Comment by InKryption** [comment]
Another thing that occurs to me is that we could generate the struct alongside the associated enum, which would require less comptime magic.

**Comment by InKryption** [comment]
@Snektron Are you very busy? If you are, I apologize, but some sort of indication as to what to do here would be appreciated.

**Comment by Snektron** [comment]
Sorry for the wait. Let try it.

**Comment by ashpil** [comment]
> > Something that was on my mind was to provide easier ways of combining function pointers from multiple extensions. My plan was to predefine a []Command for every extension, which you would be able to concatenate at build to get the complete list of commands.
> 
> It seems to me @InKryption's modifications would provide a better system for this. If you treat wrapper inputs as just normal flags, rather than an array (which technically allows repeating a command more than once), you could just do something like:
> 
> ```zig
> const commands =
>   vk.device_commands.v1_0.union(
>   vk.device_commands.swapchain.union(
>   if (windows) vk.device_commands.win32_surface else .{}));
> ```
> 
> which although possibly less ergonomic makes more semantic sense, I think - as what you're doing is identical to any other union-of-flags-ing that you might be doing in Vulkan.

Did the ability to union (merge) these ever make it?

**Comment by InKryption** [comment]
> Did the ability to union (merge) these ever make it?

It never did actually, sort of slipped my mind as soon as this change unblocked the stuff I was doing; quite inconsiderate on my part. I'll try and look at making a PR for that at some point soon, or anyone else, feel free to do so.

**Pull request merged**
