### PR TITLE
Added option to add shaders as base64 instead of embedding file

### PR DESCRIPTION
**Pull request by a-day-old-bagel**
addShaderBase64 allows for the inclusion of spv binaries without using @embedfile, since @embedfile has certain restrictions on file locations.

### CODE REVIEW

**Comment by Snektron** [comment]
Thanks for putting in the work, though im not sure if this is the correct approach. I think we can have a proper workaround, and ideally one that also integrates with the cache system a little bit more. I have something in mind, and it should be a more proper implementation rather than the half demo-style implementation there is now:

We can generate the files in cache in such a way that we can have a valid path for a zig module, which can provide the shaders. To do that we would generate the spv and resources file in the same subdirectory in cache, and then provide the latter as module. This means moving the current "resources" functionality that is in build.zig to the core library (the common build_integration.zig is probably the place for that). Note that this would make it less of an ad-hoc resources solution, and more something specifically for shaders, but I think that is fine for vulkan-zig, and a more general asset system can be provided by a different library. The directory structure would then be something like this:
```
zig-cache/
  shaders/
    spirv/
      <vertex_shader_source_hash>.spv
      <fragment_shader_source_hash>.spv
      <vertex_fragment_spv_hash>.zig
```
where the last file would contain something like
```
pub const vertex = @embedFile(...).*;
pub const fragment = @embedFile(...).*;
```

**Comment by a-day-old-bagel** [comment]
Yes, an approach like that would be good. I agree that it's probably not necessary to support non-shader resources using the same calls.

I'll just keep using my base64 approach for my own project the scheme you've suggested is complete, so that I don't have to deal with all the complaining that @embedFile does about package paths, etc.

Sounds good, thanks for the quick response.

**Comment by Snektron** [comment]
We can use this for the time being, so that the CI is at least fixed. Be warned that when resolving this properly it will likely be a breaking change.

I can probably work on it soon tm

**Comment by Snektron** [comment]
@a-day-old-bagel Looks like there was an issue with this PR where it wouldnt quite load the shaders properly. I've implemented a more proper implementation now, which also caches compiled shaders as a bonus.

**Pull request merged**
